//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace STSC_TextToGeometry_v19 {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class myCommands {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal myCommands() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("STSC_TextToGeometry_v19.myCommands", typeof(myCommands).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyCommand.
        /// </summary>
        internal static string MyCommandLocal {
            get {
                return ResourceManager.GetString("MyCommandLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyLispFunction.
        /// </summary>
        internal static string MyLispFunctionLocal {
            get {
                return ResourceManager.GetString("MyLispFunctionLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyPickFirst.
        /// </summary>
        internal static string MyPickFirstLocal {
            get {
                return ResourceManager.GetString("MyPickFirstLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySessionCmd.
        /// </summary>
        internal static string MySessionCmdLocal {
            get {
                return ResourceManager.GetString("MySessionCmdLocal", resourceCulture);
            }
        }
    }
}
